# # SQLite version 3.x
# #   gem install sqlite3
# #
# #   Ensure the SQLite 3 gem is defined in your Gemfile
# #   gem 'sqlite3'
# #

# default: &default
#   adapter: postgresql
#   pool: 5
#   encoding: unicode
#   timeout: 5000
#   port: 5432
#   username: pguser
#   password: consultadd   ### password you have specified within psql
#   host: localhost

# development:
#   <<: *default
#   database: Reddera
#   pool: 5


# test:
#   <<: *default
#   database: Reddera
#   template: template0

# production:
#   <<: *default
#   database: Reddera
development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true
  database: reddera_development
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  database: reddera_development

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  database: reddera_development
