development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  reconnect: true
  database: reddera_development
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  database: reddera_development

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  database: reddera_development
